default: &default
  adapter: postgresql
  encoding: unicode
  username: wolfpack
  password: wolfpack
  host: localhost

development:
  <<: *default
  database: wolfpack_development

test:
  <<: *default
  database: wolfpack_test
